config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html  
  devise_for :staffs, skip: [:registration, :passwords]
  devise_scope :staff do
    authenticated :staff do
      root 'pages#dashboard', as: :staff_root
      get 'account', to: 'pages#account'
      resources :products, only: [:show, :index]
      resources :suppliers, only: [:show, :index] do
        resources :orders, only: [:show, :index]
      end
      resources :stores, only: [:show, :index] do
        resources :deliveries, only: [:show, :index]
        resources :pullouts, only: [:show, :index]
        resources :transfers, only: [:show, :index]
        resources :ending_inventories, only: [:show, :index]
      end
      resources :forms, only: [:index] do
        collection do
          get 'products', to: 'forms#products', as: 'form_products'
          get 'store_products', to: 'forms#store_products', as: 'form_store_products'
        end
      end
    end
  end

  devise_for :admins
  devise_scope :admin do
    authenticated :admin do
      root 'pages#dashboard', as: :admin_root
      get 'account', to: 'pages#account', as: 'accounts'
      resources :products, except: [:destroy] do
        collection do
          post 'import', to: 'products#import'
        end
      end
      resources :suppliers, except: [:destroy] do
        resources :orders, except: [:destroy, :update, :edit, :index]
      end
      resources :stores, except: [:destroy] do
        resources :deliveries, except: [:destroy, :edit, :index]
        resources :pullouts, except: [:destroy, :edit, :update, :index]
        resources :transfers, except: [:destroy, :edit, :update, :index]
        resources :ending_inventories, except: [:destroy, :index, :edit, :update]
      end
      resources :manage_accounts, only: [:index] do
        collection do
          put 'authorize_account/:admin_id', to: 'manage_accounts#authorize', as: 'authorize_admin'
          delete 'delete_account/:admin_id', to: 'manage_accounts#delete', as: 'delete_admin'
        end
      end
      resources :staffs, except: [:index, :show]
      resources :admins, only: [:update, :destroy]
      resources :forms, only: [:index] do
        collection do
          get 'products', to: 'forms#products'
          get 'store_products', to: 'forms#store_products'
        end
      end
      resources :api, only: [] do
        collection do 
          get 'product', to: 'api#products'
          get 'store_product', to: 'api#store_products'
        end
      end
    end
  end

  if Rails.env.development?
    visualize
  end
  root 'devise/sessions#new'
end

app/models/store.rb
class Store < ApplicationRecord
    # Entity realationships
    has_many :store_products
    has_many :products, through: :store_products
    has_many :deliveries
    has_many :pullouts
    has_many :ending_inventories
    accepts_nested_attributes_for :store_products, reject_if: :all_blank, allow_destroy: true

    # Validation
    validate :contact_number_valid_length
    validates :name, :address, :contact_number, presence: true
    validate :store_products_unique
    
    def contact_number_valid_length
        if !contact_number.nil?
            if contact_number.length > 20
                errors.add(:contact_number, 'Contact number should not exceed 20 characters')
            end
        end
    end

    def store_products_unique
        products = []
        store_products.each do |store_product|        
            products << store_product.product
        end
        if products.size != products.uniq.size
            errors.add(:name,'Consignment store products must be unique.')
        end 
    end

    # Instance methods
    def transfers
        Transfer.all.where(store_from_id: id)
    end

    def clean
        store_products.each do |product|
            if product.inventory == 0
                product.delete
            end
        end
    end

    def total_sales(start_date = nil, end_date = nil)
        total_sales = 0.0
        if start_date != nil && end_date != nil
            ending_inventories.where('created_at BETWEEN ? AND ?', start_date, end_date).each do |ending_inventory|
                total_sales += ending_inventory.total_sales
            end
        else
            ending_inventories.each do |ending_inventory|
                total_sales += ending_inventory.total_sales
            end
        end
        total_sales
    end
    
    def total_cogs
        total_cogs = 0.0
        ending_inventories.each do |ending_inventory|
            total_cogs += ending_inventory.total_cogs
        end
        total_cogs
    end

    def total_products
        total_products = 0
        store_products.each do |store_product|
            total_products += store_product.inventory
        end
        total_products
    end

    def sold_items
        sold_items = 0
        if !ending_inventories.empty?
            ending_inventories.each do |ending_inventory|
                ending_inventory.ending_inventory_products.each do |ending_inventory_product|
                    sold_items += ending_inventory_product.beginning_quantity - ending_inventory_product.ending_quantity
                end
            end
        end
        sold_items
    end

    # Static Methods
    def self.total_sales
        @store = Store.all
        total_sales = 0.0
        @store.each do |store|
            total_sales += store.total_sales
        end
        total_sales
    end

    def self.total_cogs
        @store = Store.all
        total_cogs = 0.0
        @store.each do |store|
            total_cogs += store.total_cogs
        end
        total_cogs
    end

    def self.sort_by_sales(start_date=nil, end_date=nil)
        if !start_date.nil? && !end_date.nil?
            Store.all.sort_by{ |store| store.total_sales(start_date, end_date)}.reverse.take(10)
        else
            Store.all.sort_by(&:total_sales).reverse.take(10)
        end
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
    before_action :set_store, only: [:show, :edit, :update]
    def index
        if params[:store_sort] and params[:store_sort] != ""
            if params[:store_search] and params[:store_search] != ""
                q_string = '%'+params[:store_search]+'%'
                @stores = Store.paginate(page: params[:page], per_page: 9).where('name LIKE ?', q_string).order(params[:store_sort] + ' ASC')
            else
                @stores = Store.paginate(page: params[:page], per_page: 9).order(params[:store_sort] + ' ASC')
            end
        else
            if params[:store_search] and params[:store_search] != ""
                q_string = '%'+params[:store_search]+'%'
                @stores = Store.paginate(page: params[:page], per_page: 9).where('name LIKE ?', q_string)
            else
                @stores = Store.paginate(page: params[:page], per_page: 9)
            end
        end
    end

    def new
        @store = Store.new
    end

    def create
        @store = Store.new(store_params)
        if @store.save
            redirect_to store_path(@store), notice: "#{@store.name} successfully created"
        else
            render :new
        end
    end

    def show
        @products = @store.store_products.paginate(page: params[:products_page], per_page: 5).order('created_at DESC')
        @deliveries = @store.deliveries.paginate(page: params[:deliveries_page], per_page: 5).order('created_at DESC')
        @pullouts = @store.pullouts.paginate(page: params[:pullouts_page], per_page: 5).order('created_at DESC')
        @transfers = @store.transfers.paginate(page: params[:transfers_page], per_page: 5).order('created_at DESC')
        @ending_inventories = @store.ending_inventories.paginate(page: params[:ending_inventories_page], per_page: 5).order('created_at DESC')

        respond_to do |format|
            format.xls do
                headers["Content-Disposition"] =  "attachment; filename=\"Store Products #{@store.name} - #{DateTime.now.strftime('%B %d %Y')}.xls\""
            end
            format.html
        end
    end
    
    def edit
    end
    
    def update
        if @store.update(store_params)
            redirect_to store_path(@store), notice: "#{@store.name} successfully updated"
        else
            render :edit
        end
    end

    private
        def store_params
            params.require(:store).permit!
        end
        def set_store
            @store = Store.find(params[:id])
        end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<div class="ui stackable grid">
    <div class="seven wide column">
    <%= simple_form_for(@store, html: {class: 'ui form', style: 'z-index: 2'}) do |f| %>
        <div class="field">
            <%= f.input :name, label: 'Store Name' %>
        </div>
        <div class="field">
            <%= f.input :email, label: 'Email Address' %>
        </div>
        <div class="field">
            <%= f.input :address, label: 'Store Address' %>
        </div>
        <div class="field">
            <%= f.input :contact_person, label: 'Contact Person' %>
        </div>
        <div class="field">
            <%= f.input :contact_number, label: 'Contact Number' %>
        </div>
        <div id="products">
            <%= f.simple_fields_for :store_products do |sp| %>
                <% render 'store_product_fields', f: sp %>
            <% end %>
        </div>
        <% if !Product.all.empty? %>
            <div class="links">
                <%= link_to_add_association 'Add Product', f, :store_products %>
            </div>
        <% end %>
        <br>
        <% if params[:action] == 'new' %>
            <%= f.button :submit, class: 'ui button primary' %>
        <% else %>
            <%= f.button :submit, class: 'ui button positive' %>
        <% end %>
    <% end %>
    </div>
</div>

app/views/stores/_store_product_fields.html.erb
<div class="nested-fields">
    <div class="fields">
        <div class="field">
            <%= f.label :Product, style: 'font-weight: 100;'%>
            <%= f.association :product, collection: Product.all, label: false %>
        </div>
        <div class="field">
            <%= f.input :inventory, label: 'Current Quantity' %>
        </div>
        <%= link_to_remove_association 'X', f, style: 'margin-top:2em;color:#7a828a;' %>
    </div>
</div>

app/views/stores/edit.html.erb
<h1>Edit Store</h1>

<%= render 'form' %>

app/views/stores/index.html.erb
<h1>All Stores</h1>
<form class="ui form" id="index_form">
    <div class="fields">
        <div class="field" id="store_search">
            <input type="text" name="store_search" placeholder="Search for stores">
        </div>
        <div class="field" id="store_sort">
            <select name="store_sort" class="ui dropdown">
                <option value="">Sort by</option>
                <option value="name">Name</option>
                <option value="created_at">Created At</option>
                <option value="updated_at">Updated At</option>
            </select>
        </div>
        <button class="ui button secondary" id="store_search_button">SEARCH</button>
        <% if admin_signed_in? %>
            <%= link_to 'CREATE STORE', new_store_path, class: 'ui button primary', id: 'create_store_button' %>
        <% end %>
    </div>
</form>
<br>
<% if !@stores.empty? %>
    <div class="ui three stackable cards">
    <% @stores.each do |store| %>
        <div class="card store">
            <div class="content">
                <div class="header"> <%= link_to store.name, store_path(store), style: 'color:#000000;' %></div>
                <br>
                <div class="meta">
                    Total Items Sold: <%= store.sold_items %> <br>
                    Total Items Consigned: <%= store.total_products %> <br>
                    Total Sales: <%= 'Php %.2f' % store.total_sales %> <br>
                    <% if !store.deliveries.where('status = ?', false).empty?%>
                        Pending Deliveries: <%= store.deliveries.where('status = ?', false).count %>
                    <% end %>
                </div>
            </div>
            <% if admin_signed_in? %>
                <div class="extra content">
                    <% if store.total_products > 0 %>
                        <%= link_to 'PULL-OUT', new_store_pullout_path(store), class: 'ui basic default button'  %>
                    <% end %>
                    <%= link_to 'ADD DELIVERY', new_store_delivery_path(store), class: 'ui basic green button'%>
                </div>
            <% end %>
        </div>
    <% end %>
    </div>
    <br>
    <%= will_paginate @stores,renderer: WillPaginateSemanticUi::ActionView::Renderer %> 
<% else %>
  <h2>No Stores.</h2>
<% end %>

app/views/stores/new.html.erb
<h1>Create Store</h1>

<%= render 'form' %>

app/views/stores/show.html.erb
<%= link_to('< Go Back to Stores', stores_path, style: 'color:#7a828a;') %>

<br>

<table class="ui very basic table">
    <tr>
        <td>
            <h1 style="margin:0px;"><%= @store.name %></h1>
            <% if admin_signed_in? %>
                <a href="/stores/<%= @store.id %>/edit" >EDIT STORE</a>              
            <% end %>
        </td>
        <td style="text-align:right;">
            <% if admin_signed_in? %>
                <a href="/stores/<%= @store.id %>/edit#products" class="ui button primary">ADD PRODUCT</a>
                <% if @store.total_products > 0 %>
                    <%= link_to 'ADD ENDING INVENTORY', new_store_ending_inventory_path(@store), class: 'ui button green' %>
                <% end %>
                <% if !Store.all.where('id != ' + @store.id.to_s).empty? && @store.total_products > 0 %>
                    <%= link_to 'CREATE PRODUCT TRANSFER', new_store_transfer_path(@store), class: 'ui button red' %>
                <% end %>                
            <% end %>
        </td>
    </tr>
</table>

<p>Store Address: <%= @store.address.html_safe %></p>
<p>Email Address: <%= @store.email %></p>
<p>Contact Person: <%= @store.contact_person %></p>
<p>Contact Number: <%= @store.contact_number %></p>

<br>

<% if !@products.empty? %>
    <table class="ui very basic table show-table">
        <thead>
            <tr>
                <th colspan='3'>
                    <h2>List of All Store Products</h2>  
                </th>
                <th style="text-align:center;">
                    <%= link_to 'DOWNLOAD', store_path(@store, format: 'xls'), class: 'ui basic positive button' %>
                </th>
            </tr>
            <tr>
                <th>SKU</th>
                <th>Name</th>
                <th>Quantity</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <% @products.each do |product| %>
            <tr>
                <td><%= product.product.sku %></td>
                <td><%= product.product.name %></td>
                <td><%= product.inventory %></td>
                <td><%= link_to 'View', product_path(product.product) %></td>
            </tr>
            <% end %>
            <tr>
                <td colspan='4'class='paginate'>
                    <%= will_paginate @products, param_name: 'products_page', renderer: WillPaginateSemanticUi::ActionView::Renderer %>
                </td>
            </tr>
        </tbody>
    </table>  
<% end %>

<br>

<% if !@transfers.empty? %>
	<table class="ui very basic table show-table">
		<thead>
			<tr>
				<% if admin_signed_in? %>
					<th colspan='6'>
						<h2>List of all Product Transfers</h2>
					</th>
					<th style="text-align:center;">
                    <% if !Store.all.where('id != ' + @store.id.to_s).empty? && @store.total_products > 0 %>
						<%= link_to 'CREATE TRANSFER', new_store_transfer_path(@store), class: 'ui basic red button' %>
                    <% end %>
					</th>
				<% else %>					
					<th colspan='6'>
						<h2>List of all Product Transfers</h2>
					</th>
				<% end %>
			</tr>
			<tr>
				<th>Date</th>
				<th>To Store</th>
				<th>Quantity</th>
				<th colspan="4"></th>
			</tr>
		</thead>
		<tbody>
			<% @transfers.each do |transfer| %>
			<tr>
				<td><%= transfer.created_at.strftime('%b-%d-%y') %></td>
				<td><%= transfer.store_to.name %></td>
				<td><%= transfer.total_items %> units</td>
				<td><%= link_to 'View', store_transfer_path(@store, transfer) %></td>
				<td><%= link_to 'View Delivery', store_delivery_path(@store, transfer.delivery) %></td>
				<td><%= link_to 'View Pullout', store_pullout_path(transfer.store_from, transfer.pullout) %></td>
				<td><%= link_to 'Download', store_transfer_path(@store, transfer, format: :xls), style: 'color:#7a828a' %></td>
			</tr>
			<% end %>
			<tr>
                <td colspan='8'class='paginate'>
                	<%= will_paginate @transfers, param_name: 'transfers_page',renderer: WillPaginateSemanticUi::ActionView::Renderer %>      
                </td>      
			</tr>
		</tbody>
	</table>
<% end %>

<br>

<% if !@deliveries.empty? %>
    <table class="ui very basic table show-table">
        <thead>
            <tr>
                <% if admin_signed_in? %>
                    <th colspan='7'>
                        <h2>List of Store Deliveries</h2>  
                    </th>
                    <th style="text-align:center;">
                        <%= link_to 'ADD DELIVERY', new_store_delivery_path(@store), class: 'ui basic primary button' %>
                    </th>
                <% else %>
                    <th colspan='7'>
                        <h2>List of Store Deliveries</h2>  
                    </th>
                <% end %>
            </tr>
            <tr>
                <th>Date</th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Status</th>
                <th>Price</th>
                <th colspan='3'>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @deliveries.each do |delivery| %>
            <tr>
                <td><%= delivery.created_at.strftime('%d-%b-%y') %></td>
                <td><%= delivery.description %></td>
                <td><%= delivery.total_items %></td>            
                <% if delivery.status %>
                <td style="color:#08bf1b;">Delivered</td>
                <% else %>
                <td style="color:#ff5252">Pending</td>
                <% end %>
                <td><%= '%.2f' % delivery.total_price %></td>            
                <td><%= link_to 'View', store_delivery_path(@store, delivery) %></td>
                <td><%= link_to 'Download', store_delivery_path(@store, delivery, format: 'xls'), style: 'color:#7a828a' %></td>                     
                <% if admin_signed_in? %>
                    <% if delivery.status %>
                        <td style="color:#08bf1b">Change Status</td>                        
                    <% else %>
                        <td><%= link_to 'Change Status', store_delivery_path(@store,delivery), method: :patch,style: 'color:#08bf1b' %></td>
                    <% end %>
                <% end %>
            </tr>
            <% end %>
            <tr>
                <td colspan='8'class='paginate'>
                <%= will_paginate @deliveries, param_name: 'deliveries_page',renderer: WillPaginateSemanticUi::ActionView::Renderer %>      
                </td>      
            </tr>
        </tbody>
    </table>
<% end %>

<br>

<% if !@pullouts.empty? %>
    <table class="ui very basic table show-table">
        <thead>
            <tr>
                <% if admin_signed_in? %>
                    <th colspan='5'>
                        <h2>List of Store Pullouts</h2>  
                    </th>
                    <th style="text-align:center;">
                        <% if @store.total_products > 0 %>
                            <%= link_to 'ADD PULLOUT', new_store_pullout_path(@store), class: 'ui basic primary button' %>
                        <% end %>
                    </th>
                <% else %>
                    <th colspan='6'>
                        <h2>List of Store Pullout</h2>  
                    </th>
                <% end %>
            </tr>
            <tr>
                <th>Date</th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Price</th>
                <th colspan='2'>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @pullouts.each do |pullout| %>
            <tr>
                <td><%= pullout.created_at.strftime('%d-%b-%y') %></td>
                <td><%= pullout.description %></td>
                <td><%= pullout.total_items %></td>
                <td><%= '%.2f' % pullout.total_price %></td>            
                <td><%= link_to 'View', store_pullout_path(@store, pullout) %></td>
                <td><%= link_to 'Download', store_pullout_path(@store, pullout, format: 'xls'), style: 'color:#7a828a' %></td>                   
            </tr>
            <% end %>
            <tr>
                <td colspan='6' class='paginate'>
                <%= will_paginate @pullouts, param_name: 'pullouts_page',renderer: WillPaginateSemanticUi::ActionView::Renderer %>      
                </td>      
            </tr>
        </tbody>
    </table>
<% end %>

<br>

<% if !@ending_inventories.empty? %>
    <table class="ui very basic table show-table">
        <thead>
            <tr>
                <% if admin_signed_in? %>
                    <th colspan='4'>
                        <h2>List of Sales Reports</h2>  
                    </th>
                    <th style="text-align:center;">
                        <% if @store.total_products > 0 %>
                            <%= link_to 'ADD ENDING INVENTORY', new_store_ending_inventory_path(@store), class: 'ui basic primary button' %>
                        <% end %>
                    </th>
                <% else %>
                    <th colspan='5'>
                        <h2>List of Sales Reports</h2>  
                    </th>
                <% end %>
            </tr>
            <tr>
                <th>Date</th>
                <th>Total Sales</th>
                <th>Total COGS</th>
                <th colspan='2'>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @ending_inventories.each do |ending_inventory| %>
            <tr>
                <td><%= ending_inventory.created_at.strftime('%d-%b-%y') %></td>
                <td><%= 'Php %.2f' % ending_inventory.total_sales %></td>            
                <td><%= 'Php %.2f' % ending_inventory.total_cogs %></td>            
                <td><%= link_to 'View', store_ending_inventory_path(@store, ending_inventory) %></td>
                <td><%= link_to 'Download', store_ending_inventory_path(@store, ending_inventory, format: 'xls'), style: 'color:#7a828a' %></td>
            </tr>
            <% end %>
            <tr>
                <td colspan='8' class='paginate'>
                <%= will_paginate @ending_inventories, param_name: 'ending_inventories_page',renderer: WillPaginateSemanticUi::ActionView::Renderer %>
                </td>      
            </tr>
        </tbody>
    </table>
<% end %>

app/views/stores/show.xls.erb
<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet" xmlns:html="http://www.w3.org/TR/REC-html40">
    <Worksheet ss:Name="Sheet1">
        <Table>
        <Column ss:Index="1" ss:AutoFitWidth="0" ss:Width="110"/>
            <Row>
                <Cell><Data ss:Type="String">SKU</Data></Cell>
                <Cell><Data ss:Type="String">Product Name</Data></Cell>
                <Cell><Data ss:Type="String">Quantity</Data></Cell>
                <Cell><Data ss:Type="String">COGS</Data></Cell>
                <Cell><Data ss:Type="String">Sales</Data></Cell>
            </Row>
            <% @store.store_products.each do |store_product| %>
            <Row>
                <Cell><Data ss:Type="String"><%= store_product.product.sku %></Data></Cell>
                <Cell><Data ss:Type="String"><%= store_product.product.name %></Data></Cell>
                <Cell><Data ss:Type="Number"><%= store_product.inventory %></Data></Cell>
                <Cell><Data ss:Type="Number"><%= store_product.cogs %></Data></Cell>
                <Cell><Data ss:Type="Number"><%= store_product.sales %></Data></Cell>
            </Row>
            <% end %>
        </Table>
    </Worksheet>
</Workbook>