config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html  
  devise_for :staffs, skip: [:registration, :passwords]
  devise_scope :staff do
    authenticated :staff do
      root 'pages#dashboard', as: :staff_root
      get 'account', to: 'pages#account'
      resources :products, only: [:show, :index]
      resources :suppliers, only: [:show, :index] do
        resources :orders, only: [:show, :index]
      end
      resources :stores, only: [:show, :index] do
        resources :deliveries, only: [:show, :index]
        resources :pullouts, only: [:show, :index]
        resources :transfers, only: [:show, :index]
        resources :ending_inventories, only: [:show, :index]
      end
      resources :forms, only: [:index] do
        collection do
          get 'products', to: 'forms#products', as: 'form_products'
          get 'store_products', to: 'forms#store_products', as: 'form_store_products'
        end
      end
    end
  end

  devise_for :admins
  devise_scope :admin do
    authenticated :admin do
      root 'pages#dashboard', as: :admin_root
      get 'account', to: 'pages#account', as: 'accounts'
      resources :products, except: [:destroy] do
        collection do
          post 'import', to: 'products#import'
        end
      end
      resources :suppliers, except: [:destroy] do
        resources :orders, except: [:destroy, :update, :edit, :index]
      end
      resources :stores, except: [:destroy] do
        resources :deliveries, except: [:destroy, :edit, :index]
        resources :pullouts, except: [:destroy, :edit, :update, :index]
        resources :transfers, except: [:destroy, :edit, :update, :index]
        resources :ending_inventories, except: [:destroy, :index, :edit, :update]
      end
      resources :manage_accounts, only: [:index] do
        collection do
          put 'authorize_account/:admin_id', to: 'manage_accounts#authorize', as: 'authorize_admin'
          delete 'delete_account/:admin_id', to: 'manage_accounts#delete', as: 'delete_admin'
        end
      end
      resources :staffs, except: [:index, :show]
      resources :admins, only: [:update, :destroy]
      resources :forms, only: [:index] do
        collection do
          get 'products', to: 'forms#products'
          get 'store_products', to: 'forms#store_products'
        end
      end
      resources :api, only: [] do
        collection do 
          get 'product', to: 'api#products'
          get 'store_product', to: 'api#store_products'
        end
      end
    end
  end

  if Rails.env.development?
    visualize
  end
  root 'devise/sessions#new'
end

app/controllers/manage_accounts_controller.rb
class ManageAccountsController < ApplicationController
    def index
        @admins = Admin.paginate(page: params[:admins_page], per_page: 5)
        @staffs = Staff.paginate(page: params[:staffs_page], per_page: 5)
    end

    def authorize
       admin = Admin.find(params[:admin_id])
        if admin.id != 1
            if admin.status
               admin.status = false
            else
               admin.status = true
            end
            admin.save
            redirect_to manage_accounts_path, notice: "Changed the authorization level of #{admin.first_name}"
        else
            redirect_to manage_accounts_path, alert: "Cannot change the authorization level of #{admin.first_name}"
        end
    end

    def delete
        admin = Admin.find(params[:admin_id])
        name = admin.first_name
        if admin.id != 1
            admin.delete
            redirect_to manage_accounts_path, notice: "#{name}'s account has been deleted."
        else
            redirect_to manage_accounts_path, alert: "#{name}'s account cannot be deleted."
        end
    end
end

app/helpers/manage_accounts_helper.rb
module ManageAccountsHelper
end

app/views/manage_accounts/index.html.erb
<div class="ui stackable grid">
    <div class="row">
        <div class="eight wide column">
        <!--<%= link_to 'Back', '/account', class: 'ui button' %>-->
        <h1>Admin Accounts</h1>
        <table class="ui very simple table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th colspan="2" >Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @admins.each do |admin| %>
                    <% if admin != current_admin %>
                        <tr>
                            <td><%= admin.first_name + ' ' + admin.last_name %></td>
                            <td><%= admin.email %></td>
                            <% if admin.status %>
                                <td><%= link_to 'Unauthorize', authorize_admin_manage_accounts_path(admin), method: :put %></td>  
                            <% else %>
                                <td><%= link_to 'Authorize', authorize_admin_manage_accounts_path(admin), method: :put %></td>
                            <% end %>
                            <td><%= link_to 'Delete Account', delete_admin_manage_accounts_path(admin), method: :delete, data: {confirm: 'Are you sure? This can\'t be undone.'} %></td>
                        </tr>
                    <% end %>
                <% end %>
            </tbody>
        </table>
        <%= will_paginate @admins, param_name: 'admins_page',renderer: WillPaginateSemanticUi::ActionView::Renderer %>
        </div>
        <div class="eight wide column">
        &nbsp;
        <h1 style="display:inline;">Staff Accounts</h1>
        <table class="ui very simple table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th colspan="2">Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @staffs.each do |staff| %>
                    <tr>
                        <td><%= staff.first_name + ' ' + staff.last_name %></td>
                        <td><%= staff.email %></td>
                        <td><%= link_to 'Edit Profile', edit_staff_path(staff) %></td>
                        <td><%= link_to 'Delete Account', staff_path(staff), method: :delete, data: {confirm: 'Are you sure?'} %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>        
        <%= will_paginate @staffs, param_name: 'staffs_page',renderer: WillPaginateSemanticUi::ActionView::Renderer %>       
        <%= link_to 'Create a Staff Account', new_staff_path, class: 'ui button secondary' %>        
        </div>
    </div>
</div>
