config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html  
  devise_for :staffs, skip: [:registration, :passwords]
  devise_scope :staff do
    authenticated :staff do
      root 'pages#dashboard', as: :staff_root
      get 'account', to: 'pages#account'
      resources :products, only: [:show, :index]
      resources :suppliers, only: [:show, :index] do
        resources :orders, only: [:show, :index]
      end
      resources :stores, only: [:show, :index] do
        resources :deliveries, only: [:show, :index]
        resources :pullouts, only: [:show, :index]
        resources :transfers, only: [:show, :index]
        resources :ending_inventories, only: [:show, :index]
      end
      resources :forms, only: [:index] do
        collection do
          get 'products', to: 'forms#products', as: 'form_products'
          get 'store_products', to: 'forms#store_products', as: 'form_store_products'
        end
      end
    end
  end

  devise_for :admins
  devise_scope :admin do
    authenticated :admin do
      root 'pages#dashboard', as: :admin_root
      get 'account', to: 'pages#account', as: 'accounts'
      resources :products, except: [:destroy] do
        collection do
          post 'import', to: 'products#import'
        end
      end
      resources :suppliers, except: [:destroy] do
        resources :orders, except: [:destroy, :update, :edit, :index]
      end
      resources :stores, except: [:destroy] do
        resources :deliveries, except: [:destroy, :edit, :index]
        resources :pullouts, except: [:destroy, :edit, :update, :index]
        resources :transfers, except: [:destroy, :edit, :update, :index]
        resources :ending_inventories, except: [:destroy, :index, :edit, :update]
      end
      resources :manage_accounts, only: [:index] do
        collection do
          put 'authorize_account/:admin_id', to: 'manage_accounts#authorize', as: 'authorize_admin'
          delete 'delete_account/:admin_id', to: 'manage_accounts#delete', as: 'delete_admin'
        end
      end
      resources :staffs, except: [:index, :show]
      resources :admins, only: [:update, :destroy]
      resources :forms, only: [:index] do
        collection do
          get 'products', to: 'forms#products'
          get 'store_products', to: 'forms#store_products'
        end
      end
      resources :api, only: [] do
        collection do 
          get 'product', to: 'api#products'
          get 'store_product', to: 'api#store_products'
        end
      end
    end
  end

  if Rails.env.development?
    visualize
  end
  root 'devise/sessions#new'
end

app/views/layouts/_navbar.html.erb
<div class="ui top fixed menu" style="height: 4em;">
  <div class="right menu">
    <div class="ui simple dropdown item">
      <%= semantic_icon('user circle') %>
      &nbsp;
      <% if admin_signed_in? %>
        Hello, <%= current_admin.first_name %>!
      <% else %>
        Hello, <%= current_staff.first_name %>!
      <% end %>

      <div class="menu">
        <div class="item">
          <%= link_to "Account", accounts_path, style: 'color:black;' %>
        </div>
        <div class="item">
          <%= link_to "Sign Out", destroy_admin_session_path, method: :delete, style: 'color:black;' %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_navbar_bottom.html.erb
<div class="ui bottom fixed five item menu" style="z-index: 99999;">
  <% if params[:action] == 'dashboard' %>
    <a href="/" class="item" style="color:#517fff;"> <%= image_tag('icons/dashboard-active.png', size: '30x30')%></a>
  <% else %>
    <a href="/" class="item"> <%= image_tag('icons/dashboard-dark.png', size: '30x30')%></a>
  <% end %>

  <% if params[:controller] == 'products'%>
    <a href="/products" class="item" style="color:#517fff;"> <%= image_tag('icons/products-active.png', size: '30x30')%></a>        
  <% else %>
    <a href="/products" class="item"> <%= image_tag('icons/productsdark.png', size: '30x30')%></a>
  <% end %>

  <% if params[:controller] == 'stores' || params[:controller] == 'deliveries' || params[:controller] == 'pullouts' || params[:controller] == 'ending_inventories' || params[:controller] == 'transfers' %>
    <a class="item" href="/stores" style="color:#517fff;"> <%= image_tag('icons/store-active.png', size: '30x30')%></a>
  <% else %>
    <a class="item" href="/stores"> <%= image_tag('icons/store-dark.png', size: '30x30')%></a>
  <% end %>

  <% if params[:controller] == 'forms' %>
    <a class="item" href="/forms" style="color:#517fff;"> <%= image_tag('icons/copy-active.png', size: '30x30')%></a>
  <% else %>
    <a class="item" href="/forms"> <%= image_tag('icons/copy.png', size: '30x30')%></a>
  <% end %>

  <% if params[:controller] == 'suppliers' || params[:controller] == 'orders' %>
    <a class="item" href="/suppliers" style="color:#517fff;"> <%= image_tag('icons/shopping-cart-active.png', size: '30x30')%></a>
  <% else %>
    <a class="item" href="/suppliers" > <%= image_tag('icons/shopping-cart.png', size: '30x30')%>
    </a>    
  <% end %>
</div>

app/views/layouts/_popups.html.erb
<% if notice %>
    <div class="ui floating info message" style="display:block;">
        <i class="close icon"></i>
        <%= notice %>
    </div>
<% end %>
<% if alert %>
    <div class="ui floating negative message" style="display:block;">
        <i class="close icon"></i>
        <%= alert %>
    </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="ui left fixed vertical menu">
  <a href="/" class="item"> <%= image_tag('logo.png', style: 'padding-left: 3em;') %></a>

  <% if params[:action] == 'dashboard' %>
    <a href="/" class="item" style="color:#517fff;"> <%= image_tag('icons/dashboard-active.png', size: '30x30')%> &nbsp; Dashboard</a>
  <% else %>
    <a href="/" class="item"> <%= image_tag('icons/dashboard-dark.png', size: '30x30')%> &nbsp; Dashboard</a>
  <% end %>

  <% if params[:controller] == 'products'%>
    <a href="/products" class="item" style="color:#517fff;"> <%= image_tag('icons/products-active.png', size: '30x30')%> &nbsp; Products</a>        
  <% else %>
    <a href="/products" class="item"> <%= image_tag('icons/productsdark.png', size: '30x30')%> &nbsp; Products</a>    
  <% end %>

  <% if params[:controller] == 'stores' || params[:controller] == 'deliveries' || params[:controller] == 'pullouts' || params[:controller] == 'ending_inventories' || params[:controller] == 'transfers' %>
    <a class="item" href="/stores" style="color:#517fff;"> <%= image_tag('icons/store-active.png', size: '30x30')%> &nbsp; Stores</a>
  <% else %>
    <a class="item" href="/stores"> <%= image_tag('icons/store-dark.png', size: '30x30')%> &nbsp; Stores</a>    
  <% end %>

  <% if params[:controller] == 'forms' %>
    <a class="item" href="/forms" style="color:#517fff;"> <%= image_tag('icons/copy-active.png', size: '30x30')%> &nbsp; Forms</a>
  <% else %>
    <a class="item" href="/forms"> <%= image_tag('icons/copy.png', size: '30x30')%> &nbsp; Forms</a>
  <% end %>

  <% if params[:controller] == 'suppliers' || params[:controller] == 'orders' %>
    <a class="item" href="/suppliers" style="color:#517fff;"> <%= image_tag('icons/shopping-cart-active.png', size: '30x30')%> &nbsp; Suppliers</a>
  <% else %>
    <a class="item" href="/suppliers" > <%= image_tag('icons/shopping-cart.png', size: '30x30')%> &nbsp; Suppliers</a>    
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>The Craft Central Integrated Consignment System</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=7">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <%= favicon_link_tag 'icons/ink.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if admin_signed_in? || staff_signed_in? %>
    <%# Authenticated %>

      <%# Loader %>
      <div class="ui segment" style="position:fixed; height:102vh; width: 100vw; display:none; z-index: 999;" id="loader">
        <div class="ui active inverted dimmer">
          <div class="ui big text loader"><span id="load_text">Crafting</span> &hellip;</div>
        </div>
      </div>
      
      <div class="ui fluid container">
        <div class="ui stackable grid">
          <div class="row">
            <div class="three wide column">
              <%= render 'layouts/sidebar' %>
            </div>
            <div class="thirteen wide column">
              <%= render 'layouts/navbar' %>
              <%= render 'layouts/navbar_bottom' %>              
              <div id="content">
                <%= render 'layouts/popups' %>
                <%= yield %>            
              </div>
            </div>
          </div> <!--Row-->
        </div> <!--Grid-->
      </div> <!--Container-->
    <% else %>
      <%# Unauthenticated User %>
      <%= yield %>
    <% end %>

</body>
</html>